name: Build o1js
on:
  push:
    branches:
      - main

jobs:
  Build-Doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run typedoc
        run: |
          git submodule update --init --recursive
          npm ci
          npx typedoc --tsconfig tsconfig.node.json src/index.ts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
